name: Python CI

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  test-3_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8.18']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -U pip setuptools
        make install

    - name: Flake8 Compliance
      run: |
        . venv/bin/activate
        make lint

    - name: Run Unit Tests
      run: |
        . venv/bin/activate
        make test

  build:
    runs-on: ubuntu-latest
    needs: [test-3_8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.18'

    - name: Creating build
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -U pip setuptools wheel build
        python -m build
        python setup.py --version > version.txt