name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.x'
    - name: Create environment and build distribution
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -U pip setuptools wheel build
        rm -rf dist/
        python -m build
        python setup.py --version > version.txt
        
    - name: Upload version file
      uses: actions/upload-artifact@v3
      with:
        name: version
        path: version.txt

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  install_from_pypi:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    steps:
    - uses: actions/checkout@v3
    
    - name: Download version file
      uses: actions/download-artifact@v3
      with:
        name: version

    - name: Install from PyPI
      run: |
        ls -la
        cat version.txt
        python3 -m venv venv
        . venv/bin/activate
        pip install flask-3-log-request-id==`cat version.txt`
        pip freeze | grep -i flask-3-log-request-id
